title: README-for-life
logo: /assets/images/headshot.png
description: "Jason Vanderburg’s digital notebook of ideas, essays, and experiments."
show_downloads: true
url: "https://blackbluecaribou.github.io"
baseurl: "/README-for-life"
theme: jekyll-theme-minimal-mistakes

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jemoji
  - jekyll-remote-theme
